base_url = "https://lovesegfault.com"

title = "null pointer"
description = "Bernardo's ramblings and non sequuntur"

default_language = "en"
theme = "zerm"

generate_feed = true
taxonomies = [
           {name = "tags"},
           {name = "categories"},
]
compile_sass = true
minify_html = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"
render_emoji = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
author = "Bernardo Meurer"
show_author = true
show_categories = true
show_tags = true
theme_color = "green"
favicon = "favicon.png"
copyright = "Copyright &copy; 2021 - Bernardo Meurer"
center = true
logo_text = "null pointer"
