baseurl = "/"
languageCode = "en-us"
title = "null pointer"
theme = "hugo-theme-terminal"
paginate = 5

[params]
contentTypeName = "posts"
themeColor = "green"
showMenuItems = 5
showLanguageSelector = false
fullWidthTheme = false
centerTheme = true
favicon = "images/favicon.png"
showLastUpdated = false

[params.twitter]
creator = "lovesegfault"

[languages]
[languages.en]
languageName = "English"
title = "null pointer"
subtitle = "Bernardo's ramblings and non sequuntur"
owner = "Bernardo Meurer"
copyright = "Copyright &copy; 2021 - Bernardo Meurer"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "Page not found..."
missingBackButtonLabel = "Back to home page"

[languages.en.params.logo]
logoText = "null pointer"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories"
[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags"

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
[markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
[markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false
[markup.highlight]
    codeFences = true
    guessSyntax = true
