name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: experimental-features = nix-command flakes
      - name: markdownlint
        run: nix develop -c mdl content
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: experimental-features = nix-command flakes
      - name: nix-build
        run: nix build -L
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [ lint, build ]
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          lfs: true
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: experimental-features = nix-command flakes
      - name: nix-build
        run: nix build -L
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_branch: public
          publish_dir: ./result
