name: CI
on:
  push:
    branches: [master]
  pull_request:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v20
      - name: markdownlint
        run: nix develop -c mdl content
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: DeterminateSystems/nix-installer-action@v20
      - name: nix-build
        run: nix build -L
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: DeterminateSystems/nix-installer-action@v20
      - name: nix-build
        run: nix flake check
