name: update flakes
on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:
jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
          repository: lovesegfault/cv
          token: ${{ secrets.PAT }}
      - uses: cachix/install-nix-action@v14
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/ipa0c64h689jb4ys6hxsky2r8xpld0hv/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: experimental-features = nix-command flakes
      - run: git config --global user.email "hatesegfault@protonmail.ch"
      - run: git config --global user.name "hatesegfault"
      - name: Update flakes
        run: nix flake update --commit-lock-file
      - uses: peter-evans/create-pull-request@v3.10.1
        with:
          branch: flake-update
          commit-message: "flake: update"
          delete-branch: true
          title: "flake: update"
          token: ${{ secrets.PAT }}
